# Pandas: DataFrame and Series

**Pandas** provides fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both **easy and intuitive**. Pandas is also **very fast** since it builds on top of **NumPy**, which builds on top of **C**.

The community agreed alias for `pandas` is `pd`, so it has been standard practice:

In [2]:
import pandas as pd

## Read data in

Data can be loaded into a Pandas DataFrame from various sources and different formats:

1. **Databases**: relational (SQL) and unstructured (NoSQL)
2. **Surveys**: Google Forms, SurveyMonkey
3. **APIs**: Social Media Platforms, Open Street Maps, Flights, ..etc.
4. **Web Scraping**: BeautifulSoup, Scrapy, Selenium
5. **Raw Files**: csv, excel, txt, json, xml, pdf, ..etc.

Pandas provides the [`read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv "pandas.read_csv") function to read data stored as a csv file into a pandas `DataFrame`. pandas supports many different file formats or data sources out of the box (csv, excel, sql, json, parquet, …), each of them with the prefix `read_*`.

![](../assets/01/pandas_io.png)

See: [IO tools (text, CSV, HDF5, …)](https://pandas.pydata.org/docs/user_guide/io.html) for a table containing available readers and writers.

In [1]:
# Full help(pd.read_csv) is very long — show a short preview instead
print(pd.read_csv.__doc__[:600])
print("\n... (truncated; see docs for the full parameter list)")

    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/t

... (truncated; see docs for the full parameter list)

The result of a `read_*` operation is a `DataFrame` (usually abbreviated as `df`), which is essentially a **table of rows and columns**.

![Figure: Pandas' DataFrame](../assets/01/dataframe.png)

Let's demonstrate that.

### Create a data file

**Your Task**:

1. create a file named: `abc.csv`
2. type the following letters yourself into it (don't use shortcuts to copy-paste it)   
    ```csv
    a,b,c
    1,2,3
    4,5,6
    ```
3. save it in the course `data` folder (one level up from this notebook): `../data/abc.csv`

### read from file on disk into a DataFrame

In [4]:
# Best practice: use pathlib to handle file paths
from pathlib import Path

# Set the path to the directory containing the datasets
data_dir = Path('../data/')

# Debugging
print(data_dir.exists())

True

In [5]:
print(data_dir.resolve())

/home/halgoz/work/Bootcamp/ai-pros/public/courses/Data_Analysis/data

In [6]:
file_path = data_dir / 'abc.csv'

# Debugging
print(file_path.exists())

True

Once we have specified the path, we load the data into a Python object; i.e., a `DataFrame`:

In [7]:
# Notice we use `df` to denote a DataFrame
df_1 = pd.read_csv(file_path)

# Debugging
df_1.head() # show first 5 rows

   a  b  c
0  1  2  3
1  4  5  6

### Modify

In [8]:
df_1 = df_1 * 10
df_1

    a   b   c
0  10  20  30
1  40  50  60

### Write the DataFrame to csv file on disk

In [9]:
df_1.to_csv(data_dir / 'abc_2.csv', index=False)

### read from url

Alternatively, one could load the data from a url directly:

In [2]:
# Use the raw.githubusercontent.com URL (not the github.com/.../blob/... page)
data_url_wpm = (
    "https://raw.githubusercontent.com/HassanAlgoz/AAI/"
    "main/courses/Data_Analysis/data/wpm.csv"
)
df_2 = pd.read_csv(data_url_wpm)

# Debugging
df_2.tail()  # show last 5 rows

    wpm  light
21   21   True
22   37   True
23   42   True
24   36   True
25   40   True

## DataFrame Metadata

The `head`/`tail`/`info` methods and the `dtypes` attribute are convenient for a first check:

In [ ]:
# show only data types
df_2.dtypes

wpm      int64
light     bool
dtype: object

In [ ]:
# show full technical details of the DataFrame
df_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   wpm     26 non-null     int64
 1   light   26 non-null     bool
dtypes: bool(1), int64(1)
memory usage: 366.0 bytes

## Creating a DataFrame

Sometimes, like in demonstration, you need to create a `DataFrame` object, not loaded from outside.

DataFrames can be constructed from Python dictionaries, like so:

In [ ]:
df = pd.DataFrame(
    {
        'A': [10, 20, 30],
        'B': [40, 50, 60]
    }
)

df

    A   B
0  10  40
1  20  50
2  30  60

- Keys `'A'` and `'B'` become column labels
- Values become cell values

## Key Takeaways

- **DataFrames** are core to pandas: they provide labeled, 2-dimensional data structures, allowing flexible and powerful manipulation and analysis of tabular data.

- **Reading Data:** Easily load data from various sources (CSV, Excel, SQL, web, etc.) with functions like `pd.read_csv()`.

- **Quick Inspection:** Use methods such as `.head()`, `.tail()`, `.info()`, and `.dtypes` to quickly get an overview of your data.