# DataFrame: Selecting a Subset

In [ ]:
import pandas as pd

In [ ]:
titanic = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

## Select top and bottom

In [ ]:
titanic.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [ ]:
titanic.tail(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

## Select highest and lowest

In [ ]:
titanic.nlargest(3, "Age")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C

In [ ]:
titanic.nsmallest(3, "Age")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master Viljo",male,0.67,1,1,250649,14.5000,NaN,S
469,470,1,3,"Baclini, Miss Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C

## Index and Label

More than a table though, a `DataFrame` also has:

- **Index**: to access rows (by position)
- **Label**: to access columns (by name)

![Figure: Pandas' DataFrame](../assets/pandas/dataframe.png)

In [ ]:
# Show index
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [ ]:
# Show labels
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

## Series

Once you access either a row or a column, you get back a `Series` object:

In [ ]:
s = titanic['Sex']
s

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str

In [ ]:
# Type of the selected object
type(s)

pandas.Series

![](../assets/pandas/series.png)

- The left-most is the index

In [ ]:
s.index

- The values are it's column


- The bottom-line is the label `Sex` with Length and `dtype`; which is the type of the values in the series

In [ ]:
# Type of the values in the Series:
s.dtype.type

str

## Select specific columns

![](../assets/pandas/subset_columns.png)

In [11]:
# Select specific columns
df_subset = titanic[['Name', 'Age', 'Sex']]
df_subset.head()

                                                Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                              Heikkinen, Miss Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male

## Select specific rows

![](../assets/pandas/subset_rows.png)

To select rows based on a conditional expression, use a condition inside the selection brackets `[]`, like so:

In [12]:
above_35 = titanic[titanic["Age"] > 35]

In [13]:
above_35.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

Notice the index shows: `1`, `6`, `11`, `13` and `15`, which are the location of these rows in the original `DataFrame`.

### Boolean Mask (Binary Vector)

The condition inside the selection brackets `titanic["Age"] > 35` checks for which rows the `Age` column has a value larger than 35. It is also known as a **boolean mask**, since it results in a `Series` of `True`/`False` values:

In [14]:
titanic["Age"] > 35

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

Only rows for which the value is `True` will be selected.

## Combine row selection conditions

When combining multiple conditional statements, be careful:

1. each condition must be surrounded by parentheses `()`
2. you can not use `or`/`and` but need to use the or **operator `|`** and the **and operator `&`**.

In [15]:
# Condition 1
mask_1 = titanic["Age"] > 35

# Condition 2
mask_2 = titanic["Pclass"].isin([2, 3])

# Combine conditions
mask = mask_1 & mask_2

# Apply the mask to the DataFrame
above_35_df = titanic[mask]
above_35_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S

## Select specific rows AND columns

![](../assets/pandas/subset_rows_and_columns.png)

Let's say, we're interested in the names of the passengers older than 65 years.

When selecting both rows AND columns, We can't just use the brackets `[]` notation directly, rather, we need to preceed add a `loc` or `iloc` method:

1. Use `loc` for label-based selection (using row/column names)
2. Use `iloc` for position-based selection (using table positions)

#### `loc`: label-based selection

In [16]:
seniors_names = titanic.loc[titanic["Age"] > 65, "Name"]
seniors_names.head()

33                    Wheadon, Mr. Edward H
96                Goldschmidt, Mr. George B
116                    Connors, Mr. Patrick
493                 Artagaveytia, Mr. Ramon
630    Barkworth, Mr. Algernon Henry Wilson
Name: Name, dtype: str

When using either `loc` or `iloc`:

1. the part before the comma is the **rows** you want
2. the part after the comma is the **columns** you want to select

Let's demonstrate combining conditions and multiple column selection:

In [17]:
condition = (titanic["Age"] > 65) & (titanic['Sex'] == 'male')
columns = ["Name", 'Pclass']

seniors = titanic.loc[condition, columns]
seniors.head()

                                     Name  Pclass
33                  Wheadon, Mr. Edward H       2
96              Goldschmidt, Mr. George B       1
116                  Connors, Mr. Patrick       3
493               Artagaveytia, Mr. Ramon       1
630  Barkworth, Mr. Algernon Henry Wilson       1

To demonstrate using the result, let's say we want to know the first names these people have:

In [18]:
# convert Series to a Python list
names = seniors['Name'].to_list()

# show only first names
first_names = [x.split(',')[1].strip() for x in names]
first_names

['Mr. Edward H',
 'Mr. George B',
 'Mr. Patrick',
 'Mr. Ramon',
 'Mr. Algernon Henry Wilson',
 'Mr. Henry Michael',
 'Capt. Edward Gifford',
 'Mr. Johan']

#### `iloc`: position-based selection

In [19]:
titanic.iloc[2:5, 0:3]

   PassengerId  Survived  Pclass
2            3         1       3
3            4         1       1
4            5         0       3

- Row-wise, we are selecting from `2` to `5`
- Column-wise, we are selecting from `0` to `3`

## Timeseries Selection

Dates and strings that parse to timestamps can be passed as indexing parameters:

In [ ]:
import pandas as pd

idx = pd.date_range("2018-01-01", periods=5, freq="h")
ts = pd.Series(range(len(idx)), index=idx)
ts

## Sorting

Pandas supports three kinds of sorting:

1. by index labels
2. by column values
3. by a combination of both

First, let's set the `"PassengerId"` column as the index of the DataFrame:

In [32]:
df = titanic.set_index("PassengerId")
df.head(3)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

### 1. By Index Labels

Use `sort_index()` to sort by the row labels.

In [ ]:
# Sort descending by the index (PassengerId)
sorted_by_index = df.sort_index(ascending=False)
sorted_by_index.head(3)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S

### 2. By Column Values

Use `sort_values()` and pass the column name(s) to the `by` parameter.

In [34]:
# Sort ascending by the column (Age)
sorted_by_age = df.sort_values(by="Age", ascending=True)
sorted_by_age.head(3)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
804,1,3,"Thomas, Master Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
756,1,2,"Hamalainen, Master Viljo",male,0.67,1,1,250649,14.5000,NaN,S
470,1,3,"Baclini, Miss Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C

### 3. By a Combination of Both

You can pass both column names and the index name to `sort_values()` to sort by a combination.

In [35]:
# Sort by Ticket Class (column), then resolve ties by PassengerId (index)
sorted_by_both = df.sort_values(by=["Pclass", "PassengerId"])
sorted_by_both.head(3)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

## Key Takeaways

- **Select top and bottom** using `head(n)` and `tail(n)`
- **Select highest and lowest** using `nlargest(n)` and `nsmallest(n)`
- **Selecting** works as follows:  

    | Operation                      | Syntax          | Result    |
    | ------------------------------ | --------------- | --------- |
    | Select column                  | `df["a"]`       | Series    |
    | Select muliple columns         | `df[["a", "b"]]`       | Series    |
    | Select rows by a boolean mask (and select columns)  | `df[bool_mask, ["a", "b"]]`  | DataFrame |
    | Select a row by integer position | `df.iloc[pos]`  | Series    |
    | Slice rows by integer position (exclusive) | `df.iloc[5:10]`      | DataFrame |
    | Slice rows by label (inclusive)            | `df.loc['A':'C']`      | DataFrame |


    Source: https://pandas.pydata.org/docs/user_guide/dsintro.html#indexing-selection
    
- **Chaining Conditions:** Combine multiple boolean conditions with `&` (and), `|` (or), using parentheses as needed.

- **Sorting** DataFrame using: `sort_index()` or `sort_values(by=)`